# Generated by Django 2.0.3 on 2018-03-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='visited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
